spring:
  application:
    name: orm
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cnpag98l6cac73a6cong-a/practice_xj1n
    username: "park"
    password: lfxrPoHx9z6T6qpvWmvg1g4H4sI70q9n
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true